
services:

  mysql:

    image: mysql:8.0
    container_name: donation-mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d


  backend:

    build:
      context: ./back-end
    container_name: donation-api
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - .env

      
  frontend:

    build:
      context: ./front-end
    container_name: donation-front
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./front-end:/app
      - /app/node_modules

    stdin_open: true
    tty: true

volumes:
  mysql_data:



