SET SESSION FOREIGN_KEY_CHECKS=0;

USE railway;

INSERT INTO `user` VALUES   (1, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_ADMIN', 'joao'),
                            (2, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_ADMIN', 'hedelvan'),
                            (3, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_ADMIN', 'ezequiel'),
                            (4, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_ADMIN', 'elias'),
                            (5, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_ADMIN', 'welligton'),


                            (200, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor200'),
                            (201, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor201'),
                            (202, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor202'),
                            (203, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor203'),
                            (204, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor204'),
                            (205, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor205'),
                            (206, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor206'),
                            (207, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor207'),
                            (208, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor208'),
                            (209, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor209'),
                            (210, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor210'),
                            (211, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor211'),
                            (212, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor212'),
                            (213, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor213'),
                            (214, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor214'),
                            (215, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor215'),
                            (216, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor216'),
                            (217, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor217'),
                            (218, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor218'),
                            (219, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_DONOR', 'donor219'),
                            
                
                            (100, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin100'),
                            (101, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin101'),
                            (102, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin102'),
                            (103, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin103'),
                            (104, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin104'),
                            (105, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin105'),
                            (106, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin106'),
                            (107, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin107'),
                            (108, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin108'),
                            (109, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin109'),
                            (110, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin110'),
                            (111, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin111'),
                            (112, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin112'),
                            (113, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin113'),
                            (114, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin114'),
                            (115, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin115'),
                            (116, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin116'),
                            (117, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin117'),
                            (118, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin118'),
                            (119, TRUE, '$2a$10$zArhMpAXoIhDRvqmJSPI2uDJbGxoQft9g2LCa.7fBCOXDuqKVC6cS', 'ROLE_INSTITUTION', 'admin119');



INSERT INTO `address` VALUES (1, 'Rio Branco', 'Brasil', 'Bairro Placas', 'Estrada-Placas', '358', '69911001', 'Acre'),
                             (2, 'Rio Branco', 'Brasil', 'Bairro Centro', 'Rua Cazuza', '35', '69911002', 'Acre'),
                             (3, 'Rio Branco', 'Brasil', 'Bairro Calafate', 'Rua Tim Maia', '10', '69911003', 'Acre'),
                             (4, 'Rio Branco', 'Brasil', 'Bairro Sobral', 'Rua Caju', '358', '69911001', 'Acre'),
                             (5, 'Rio Branco', 'Brasil', 'Bairro Cidade do Povo', 'Rua Alta-D', '35', '69911002', 'Acre'),
                             (6, 'Cruzeiro do Sul', 'Brasil', 'Bairro 10', 'Rua Tucano', '100', '69911113', 'Acre'),
                             (7, 'Cruzeiro do Sul', 'Brasil', 'Bairro 15',  'Rua do Rei', '3548', '69911881', 'Acre'),
                             (8, 'Cruzeiro do Sul', 'Brasil', 'Bairro Mamão', 'Rua Central', '315', '69911662', 'Acre'),
                             (9, 'Cruzeiro do Sul', 'Brasil', 'Bairro Flamengo', 'Rua Zico', '3158', '69911551', 'Acre'),
                             (10, 'Cruzeiro do Sul', 'Brasil', 'Bairro do Vasco', 'Rua Dinamite', '115', '69911552', 'Acre'),
                             (11, 'Rio Branco', 'Brasil', 'Bairro Bosque', 'Rua do Peixe', '109', '69911873', 'Acre'),
                             (12, 'Rio Branco', 'Brasil', 'Bairro Esperança 2', 'Rua dos Dogs', '180', '69911343', 'Acre'),
                             (13, 'Rio Branco', 'Brasil', 'Bairro Manoel Julião', 'Rua Gatos', '3658', '69911231', 'Acre'),
                             (14, 'Rio Branco', 'Brasil', 'Bairro Jequitibá', 'Rua da Lagarta', '15', '69911652', 'Acre'),
                             (15, 'Bujari', 'Brasil', 'Bairro do Futebol', 'Rua Imperador', '911', '69914403', 'Acre'),
                             (16, 'Bujari', 'Brasil', 'Bairro do Vôlei', 'Rua do Poliana', '385', '69912201', 'Acre'),
                             (17, 'Jordão', 'Brasil', 'Bairro do Basquete', 'Rua do Boban Marjanovic', '148', '69916503', 'Acre'),
                             (18, 'Jordão', 'Brasil', 'Bairro do Peteca', 'Rua do Boban Marjanovic - 2', '1482', '69919503', 'Acre'),
                             (19, 'Capixaba', 'Brasil', 'Bairro da Sinuca', 'Rua do Baianinho', '1354', '69916601', 'Acre'),
                             (20, 'Feijó', 'Brasil', 'Bairro do Truco', 'Rua do Tento', '315', '69911542', 'Acre'),
                             (21, 'Rio Branco', 'Brasil', 'Bairro Placas', 'Estrada-Placas', '358', '69911001', 'Acre'),
                             (22, 'Rio Branco', 'Brasil', 'Bairro Centro', 'Rua Cazuza', '35', '69911002', 'Acre'),
                             (23, 'Rio Branco', 'Brasil', 'Bairro Calafate', 'Rua Tim Maia', '10', '69911003', 'Acre'),
                             (24, 'Rio Branco', 'Brasil', 'Bairro Sobral', 'Rua Caju', '358', '69911001', 'Acre'),
                             (25, 'Rio Branco', 'Brasil', 'Bairro Cidade do Povo', 'Rua Alta-D', '35', '69911002', 'Acre'),
                             (26, 'Cruzeiro do Sul', 'Brasil', 'Bairro 10', 'Rua Tucano', '100', '69911113', 'Acre'),
                             (27, 'Cruzeiro do Sul', 'Brasil', 'Bairro 15',  'Rua do Rei', '3548', '69911881', 'Acre'),
                             (28, 'Cruzeiro do Sul', 'Brasil', 'Bairro Mamão', 'Rua Central', '315', '69911662', 'Acre'),
                             (29, 'Cruzeiro do Sul', 'Brasil', 'Bairro Flamengo', 'Rua Zico', '3158', '69911551', 'Acre'),
                             (30, 'Cruzeiro do Sul', 'Brasil', 'Bairro do Vasco', 'Rua Dinamite', '115', '69911552', 'Acre'),
                             (31, 'Rio Branco', 'Brasil', 'Bairro Bosque', 'Rua do Peixe', '109', '69911873', 'Acre'),
                             (32, 'Rio Branco', 'Brasil', 'Bairro Esperança 2', 'Rua dos Dogs', '180', '69911343', 'Acre'),
                             (33, 'Rio Branco', 'Brasil', 'Bairro Manoel Julião', 'Rua Gatos', '3658', '69911231', 'Acre'),
                             (34, 'Rio Branco', 'Brasil', 'Bairro Jequitibá', 'Rua da Lagarta', '15', '69911652', 'Acre'),
                             (35, 'Bujari', 'Brasil', 'Bairro do Futebol', 'Rua Imperador', '911', '69914403', 'Acre'),
                             (36, 'Bujari', 'Brasil', 'Bairro do Vôlei', 'Rua do Poliana', '385', '69912201', 'Acre'),
                             (37, 'Jordão', 'Brasil', 'Bairro do Basquete', 'Rua do Boban Marjanovic', '148', '69916503', 'Acre'),
                             (38, 'Capixaba', 'Brasil', 'Bairro da Sinuca', 'Rua do Baianinho', '1354', '69916601', 'Acre'),
                             (39, 'Feijó', 'Brasil', 'Bairro do Truco', 'Rua do Tento', '315', '69911542', 'Acre'),
                             (40, 'Feijó', 'Brasil', 'Bairro do Truco', 'Rua do Tento', '315', '69911542', 'Acre'),
                             (41, 'Bujari', 'Brasil', 'Bairro do Vôlei', 'Rua do Poliana', '385', '69912201', 'Acre'),
                             (42, 'Jordão', 'Brasil', 'Bairro do Basquete', 'Rua do Boban Marjanovic', '148', '69916503', 'Acre'),
                             (43, 'Capixaba', 'Brasil', 'Bairro da Sinuca', 'Rua do Baianinho', '1354', '69916601', 'Acre'),
                             (44, 'Feijó', 'Brasil', 'Bairro do Truco', 'Rua do Tento', '315', '69911542', 'Acre'),
                             (45, 'Feijó', 'Brasil', 'Bairro do Truco', 'Rua do Tento', '315', '69911542', 'Acre');
                             
                            

INSERT INTO `administrator` VALUES (1, TRUE, 'user.jpg', 'admin01@email.com', 'Primeiro Administrador', 41, 1),
                                   (2, TRUE, 'user.jpg', 'admin02@email.com', 'Segundo Administrador', 42, 2),
                                   (3, TRUE, 'user.jpg', 'admin03@email.com', 'Terceiro Administrador', 43, 3),
                                   (4, TRUE, 'user.jpg', 'admin04@email.com', 'Quarto Administrador', 44, 4),
                                   (5, TRUE, 'user.jpg', 'admin05@email.com', 'Quinto Administrador', 45, 5);

INSERT INTO `donor` VALUES (1, TRUE, '2019-01-15', 'user.jpg', '14723843507', 'miguel4lmeida@email.com', 'Miguel Almeida de Azevedo', 'MASCULINO', 40, 200),
                           (2, TRUE, '2018-08-19', 'user.jpg', '76637495883', 'andremerli74@gmail.com', 'Davi Braga Barros', 'MASCULINO', 21, 201),
                           (3, TRUE, '2014-02-15', 'user.jpg', '43980266141', 'zxhbpg@jmurip.com', 'Arthur Bahiense Campos,', 'MASCULINO', 22, 202),
                           (4, TRUE, '2019-01-11', 'user.jpg', '43687198758', 'pmlxew@veracg.com', 'Sophia Cardoso Correia', 'FEMININO', 23, 203),
                           (5, TRUE, '2018-08-12', 'user.jpg', '21815423099', 'cgbvud@lxvhhq.com	', 'Alice Correia Castro', 'FEMININO', 24, 204),
                           (6, TRUE, '2014-02-13', 'user.jpg', '94575572390', 'carmed@usp.br', 'Julia da Costa Fontes ', 'FEMININO', 25, 205),
                           (7, TRUE, '2019-01-14', 'user.jpg', '78537194506', 'caueameni@gmail.com', 'Pedro Fontes Guimarães', 'MASCULINO', 26, 206),
                           (8, TRUE, '2018-08-15', 'user.jpg', '98152426520', 'dfqjjd@fettiv.com', 'Gabriel Magalhães', 'MASCULINO', 27, 207),
                           (9, TRUE, '2014-02-16', 'user.jpg', '43176873131', 'ucmnyo@afyyrn.com', 'Bernardo Macedo Matos', 'MASCULINO', 28, 208),
                           (10, TRUE, '2019-01-18', 'user.jpg', '37743572340', 'edw_drum@hotmail.com', 'Isabella Pedreira Queirós', 'FEMININO', 29, 209),
                           (11, TRUE, '2018-08-19', 'user.jpg', '11136641343', 'etechy@tre-pr.jus.br', 'Manuela Queirós Ribeiro', 'FEMININO', 30, 210),
                           (12, TRUE, '2014-02-10', 'user.jpg', '31037472926', 'feliperepresentante@yahoo.com.br', 'Laura Siqueira', 'FEMININO', 31, 211),
                           (13, TRUE, '2019-01-18', 'user.jpg', '85857083443', 'prof.janderfisica@gmail.com', 'Lucas Silva Ribeiro', 'MASCULINO', 32, 212),
                           (14, TRUE, '2018-08-16', 'user.jpg', '38171502296', 'matheus_campos@email.com', 'Matheus Bahiense Campos', 'MASCULINO', 33, 213),
                           (15, TRUE, '2014-02-15', 'user.jpg', '23763292136', 'rafaelazevedo01@gmail.com', 'Rafael Azevedo Cardoso', 'MASCULINO', 34, 214),
                           (16, TRUE, '2019-01-14', 'user.jpg', '81621916740', 'alvezluiza@bol.com.br', 'Luiza Alves Guimarães', 'FEMININO', 35, 215),
                           (17, TRUE, '2018-08-13', 'user.jpg', '71969737638', 'limaribeiro@yahoo.com', 'Valentina Lima Ribeiro', 'FEMININO', 36, 216),
                           (18, TRUE, '2014-02-12', 'user.jpg', '45331495109', 'braga_giovanna@outlook.com', 'Giovanna Braga Ferreira', 'FEMININO', 37, 217),
                           (19, TRUE, '2019-01-12', 'user.jpg', '45363378302', 'heitor_costaover@gmail.com', 'Heitor Costa de Oliveira', 'MASCULINO', 38, 218),
                           (20, TRUE, '2018-08-11', 'user.jpg', '38793347308', 'santos_eduarda@yahoo.com', 'Maria Eduarda Santos', 'FEMININO', 39, 219);

INSERT INTO `institution` VALUES (1, 'Sobre', TRUE, '00000000000001', 'Associação Aliança de Misericórdia - LTDA', 'img54.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física,  uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Associação Aliança de Misericórdia', 'link alternate', 'link main', 'Missão', '2020-01-19', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 1, 100),

                                 (2, 'Sobre', TRUE, '00000000000002', 'AMIGOS DO BEM - LTDA', 'img55.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'AMIGOS DO BEM', 'link alternate', 'link main', 'Missão', '2015-05-02', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 2, 101),

                                 (3, 'Sobre', TRUE, '00000000000003', 'APAE - LTDA', 'img21.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'APAE ACRE', 'link alternate', 'link main', 'Missão', '2015-05-12', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 3, 102),

                                 (4, 'Sobre', TRUE, '00000000000004', 'Associação de Apoio à Criança com Câncer - LTDA', 'img34.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Associação de Apoio à Criança com Câncer', 'link alternate', 'link main', 'Missão', '2015-07-07', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 4, 103),

                                (5, 'Sobre', TRUE, '00000000000005', 'Casa da Criança e do Adolescente Bujari - LTDA', 'img45.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Casa da Criança e do Adolescente do Bujari', 'link alternate', 'link main', 'Missão', '1995-12-05', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 5, 104),

                                 (6, 'Sobre', TRUE, '00000000000006', 'Cidade Escola Aprendiz - LTDA', 'img44.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Cidade Escola Aprendiz', 'link alternate', 'link main', 'Missão', '2015-05-12', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 6, 105),

                                 (7, 'Sobre', TRUE, '00000000000007', 'Conectas Direitos Humanos - LTDA', 'img33.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Conectas Direitos Humanos', 'link alternate', 'link main', 'Missão', '2008-05-11', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 7, 106),

                                 (8, 'Sobre', TRUE, '00000000000008', 'Centro de Recuperação e Educação Nutricional', 'img32.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'CREN - Centro de Recuperação e Educação Nutricional', 'link alternate', 'link main', 'Missão', '2015-01-05', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 8, 107),

                                 (9, 'Sobre', TRUE, '00000000000009', 'Fundação Gol de Letra - LTDA', 'img31.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Fundação Gol de Letra', 'link alternate', 'link main', 'Missão', '2015-03-19', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 9, 108),
                                
                                 (11, 'Sobre', TRUE, '00000000000011', 'Instituto Brasil Solidário - LTDA', 'img30.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Instituto Brasil Solidário', 'link alternate', 'link main', 'Missão', '2020-01-19', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 11, 110),

                                 (12, 'Sobre', TRUE, '00000000000012', 'Instituto C - LTDA', 'img29.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Instituto C - Criança, Cuidado, Cidadão', 'link alternate', 'link main', 'Missão', '2015-05-02', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 12, 111),

                                 (13, 'Sobre', TRUE, '00000000000013', 'Instituto do Câncer Infantil', 'img28.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Instituto do Câncer Infantil', 'link alternate', 'link main', 'Missão', '2015-05-12', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 13, 112),

                                 (14, 'Sobre', TRUE, '00000000000014', 'Luta pela Paz - LTDA', 'img21.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Luta pela Paz - ACRE', 'link alternate', 'link main', 'Missão', '2015-07-07', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 14, 113),

                                 (15, 'Sobre', TRUE, '00000000000015', 'Operação Sorriso CS - LTDA', 'img22.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Operação Sorriso Cruzeiro', 'link alternate', 'link main', 'Missão', '1995-12-05', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 15, 114),

                                 (16, 'Sobre', TRUE, '00000000000016', 'TETO Brasil - LTDA', 'img23.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'TETO Brasil', 'link alternate', 'link main', 'Missão', '2015-05-12', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 16, 115),

                                 (17, 'Sobre', TRUE, '00000000000017', 'Saúde Criança - LTDA', 'img24.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Saúde Criança - Capixaba', 'link alternate', 'link main', 'Missão', '2008-05-11', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 17, 116),

                                 (18, 'Sobre', TRUE, '00000000000018', 'Rede Cidadã - LTDA', 'img25.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Rede Cidadã - ACRE', 'link alternate', 'link main', 'Missão', '2015-01-05', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 18, 117),

                                 (19, 'Sobre', FALSE, '00000000000019', 'Projeto Providência - LTDA', 'img26.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Projeto Providência', 'link alternate', 'link main', 'Missão', '2015-03-19', FALSE, 'Telefone', 'Reumo', 'Valor', 'Visão', 19, 118),

                                 (20, 'Sobre', TRUE, '00000000000020', 'Projeto Casulo - LTDA', 'img27.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Projeto Casulo', 'link alternate', 'link main', 'Missão', '2015-06-11', TRUE, 'Telefone', 'Reumo', 'Valor', 'Visão', 20, 119),
                                
                                 (10, 'Sobre', FALSE, '00000000000021', 'Fundo ELAS - LTDA', 'img101.jpg', 'Criada a partir de um patrimônio doado por uma pessoa física, uma família ou uma empresa. A doação pode salvar vidas.', 'email@email', 'Fundo ELAS', 'link alternate', 'link main', 'Missão', '2004-06-21', FALSE, 'Telefone', 'Reumo', 'Valor', 'Visão', 10, 109);
                                

INSERT INTO `campaign` VALUES   (1, TRUE, 'SOCIAL', 'img114.jpg', 'As informações sobre a situação dos indígenas Yanomami em Roraima são estarrecedoras. Muitas crianças e adultos estão em situação de subnutrição neste exato momento.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude a CUFA no combate a desnutrição em Roraima', 1),
                                (2, TRUE, 'SOCIAL', 'img113.jpg', 'A doação é uma das linguagens mais belas do amor.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Espalhe esperança todos os dias', 1),
                                (3, TRUE, 'SOCIAL', 'img112.jpg', 'Doação é amor em dobro: preenche o coração de quem dá e de quem recebe.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doação para salvar vidas', 1),
                                (4, TRUE, 'SOCIAL', 'img111.jpg', 'O amor cresce com a doação. O amor que damos é o único que mantemos. A única maneira de ter amor é oferecê-lo aos outros.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ter amor é oferecê-lo aos outros', 1),
                                (5, TRUE, 'SOCIAL', 'img110.jpg', 'Doação não precisa ser apenas material, ela pode ser espiritual. Reze, doe mais amor!', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude Hoje', 1),
                                (6, TRUE, 'SOCIAL', 'img109.jpg', 'Ajude na doação de produtos de limpeza para as famílias que estão precisando.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Limpeza solidária', 1),
                                (7, TRUE, 'SOCIAL', 'img108.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 1),
                                (8, TRUE, 'SOCIAL', 'img107.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 1),
                                (9, TRUE, 'SOCIAL', 'img106.jpg', 'As informações sobre a situação dos indígenas Yanomami em Roraima são estarrecedoras. Muitas crianças e adultos estão em situação de subnutrição neste exato momento.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude a CUFA no combate a desnutrição em Roraima', 2),
                                (10, TRUE, 'SOCIAL', 'img105.jpg', 'A doação é uma das linguagens mais belas do amor.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Espalhe esperança todos os dias', 2),
                                (11, TRUE, 'SOCIAL', 'img104.jpg', 'Doação é amor em dobro: preenche o coração de quem dá e de quem recebe.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doação para salvar vidas', 2),
                                (12, TRUE, 'SOCIAL', 'img103.jpg', 'O amor cresce com a doação. O amor que damos é o único que mantemos. A única maneira de ter amor é oferecê-lo aos outros.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ter amor é oferecê-lo aos outros', 2),
                                (13, TRUE, 'SOCIAL', 'img102.jpg', 'Doação não precisa ser apenas material, ela pode ser espiritual. Reze, doe mais amor!', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude Hoje', 3),
                                (14, TRUE, 'SOCIAL', 'img101.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 3),
                                (15, TRUE, 'SOCIAL', 'img99.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 3),
                                (16, TRUE, 'SOCIAL', 'img98.jpg', 'As informações sobre a situação dos indígenas Yanomami em Roraima são estarrecedoras. Muitas crianças e adultos estão em situação de subnutrição neste exato momento.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude a CUFA no combate a desnutrição em Roraima', 3),
                                (17, TRUE, 'SOCIAL', 'img97.jpg', 'A doação é uma das linguagens mais belas do amor.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Espalhe esperança todos os dias', 4),
                                (18, TRUE, 'SOCIAL', 'img96.jpg', 'Doação é amor em dobro: preenche o coração de quem dá e de quem recebe.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doação para salvar vidas', 4),
                                (19, TRUE, 'SOCIAL', 'img95.jpg', 'O amor cresce com a doação. O amor que damos é o único que mantemos. A única maneira de ter amor é oferecê-lo aos outros.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ter amor é oferecê-lo aos outros', 4),
                                (20, TRUE, 'SOCIAL', 'img94.jpg', 'Doação não precisa ser apenas material, ela pode ser espiritual. Reze, doe mais amor!', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude Hoje', 4),
                                (21, TRUE, 'SOCIAL', 'img93.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 5),
                                (22, TRUE, 'SOCIAL', 'img92.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 5),
                                (23, TRUE, 'SOCIAL', 'img91.jpg', 'As informações sobre a situação dos indígenas Yanomami em Roraima são estarrecedoras. Muitas crianças e adultos estão em situação de subnutrição neste exato momento.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude a CUFA no combate a desnutrição em Roraima', 5),
                                (24, TRUE, 'SOCIAL', 'img90.jpg', 'A doação é uma das linguagens mais belas do amor.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Espalhe esperança todos os dias', 5),
                                (25, TRUE, 'SOCIAL', 'img89.jpg', 'Doação é amor em dobro: preenche o coração de quem dá e de quem recebe.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doação para salvar vidas', 6),
                                (26, TRUE, 'SOCIAL', 'img88.jpg', 'O amor cresce com a doação. O amor que damos é o único que mantemos. A única maneira de ter amor é oferecê-lo aos outros.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ter amor é oferecê-lo aos outros', 6),
                                (27, TRUE, 'SOCIAL', 'img87.jpg', 'Doação não precisa ser apenas material, ela pode ser espiritual. Reze, doe mais amor!', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude Hoje', 6),
                                (28, TRUE, 'SOCIAL', 'img86.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 6),
                                (29, TRUE, 'SOCIAL', 'img85.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 7),
                                (30, TRUE, 'SOCIAL', 'img84.jpg', 'As informações sobre a situação dos indígenas Yanomami em Roraima são estarrecedoras. Muitas crianças e adultos estão em situação de subnutrição neste exato momento.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude a CUFA no combate a desnutrição em Roraima', 7),
                                (31, TRUE, 'SOCIAL', 'img83.jpg', 'A doação é uma das linguagens mais belas do amor.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Espalhe esperança todos os dias', 7),
                                (32, TRUE, 'SOCIAL', 'img82.jpg', 'Doação é amor em dobro: preenche o coração de quem dá e de quem recebe.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doação para salvar vidas', 8),
                                (33, TRUE, 'SOCIAL', 'img81.jpg', 'O amor cresce com a doação. O amor que damos é o único que mantemos. A única maneira de ter amor é oferecê-lo aos outros.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ter amor é oferecê-lo aos outros', 8),
                                (34, TRUE, 'SOCIAL', 'img80.jpg', 'Doação não precisa ser apenas material, ela pode ser espiritual. Reze, doe mais amor!', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude Hoje', 8),
                                (35, TRUE, 'SOCIAL', 'img79.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 8),
                                (36, TRUE, 'SOCIAL', 'img78.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 9),
                                (37, TRUE, 'SOCIAL', 'img77.jpg', 'As informações sobre a situação dos indígenas Yanomami em Roraima são estarrecedoras. Muitas crianças e adultos estão em situação de subnutrição neste exato momento.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude a CUFA no combate a desnutrição em Roraima', 9),
                                (38, TRUE, 'SOCIAL', 'img76.jpg', 'A doação é uma das linguagens mais belas do amor.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Espalhe esperança todos os dias', 9),
                                (39, TRUE, 'SOCIAL', 'img75.jpg', 'Doação é amor em dobro: preenche o coração de quem dá e de quem recebe.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doação para salvar vidas', 8),
                                (40, TRUE, 'SOCIAL', 'img74.jpg', 'O amor cresce com a doação. O amor que damos é o único que mantemos. A única maneira de ter amor é oferecê-lo aos outros.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ter amor é oferecê-lo aos outros', 5),
                                (41, TRUE, 'SOCIAL', 'img73.jpg', 'Doação não precisa ser apenas material, ela pode ser espiritual. Reze, doe mais amor!', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Ajude Hoje', 3),
                                (42, TRUE, 'SOCIAL', 'img72.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 4),
                                (43, TRUE, 'SOCIAL', 'img71.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 1),                                
                                (44, TRUE, 'SOCIAL', 'img70.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 6),
                                (45, TRUE, 'SOCIAL', 'img69.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 4),                                
                                (46, TRUE, 'SOCIAL', 'img68.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 2),
                                (47, TRUE, 'SOCIAL', 'img67.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 3),                                
                                (48, TRUE, 'SOCIAL', 'img66.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 4),
                                (49, TRUE, 'SOCIAL', 'img65.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 2),                                
                                (50, TRUE, 'SOCIAL', 'img64.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 5),
                                (51, TRUE, 'SOCIAL', 'img63.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 12),                                
                                (52, TRUE, 'SOCIAL', 'img62.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 6),
                                (53, TRUE, 'SOCIAL', 'img61.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 11),                                
                                (54, TRUE, 'SOCIAL', 'img60.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 7),
                                (55, TRUE, 'SOCIAL', 'img59.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 6),                                
                                (56, TRUE, 'SOCIAL', 'img58.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 5),
                                (57, TRUE, 'SOCIAL', 'img57.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 4),                                
                                (58, TRUE, 'SOCIAL', 'img56.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 3),
                                (59, TRUE, 'SOCIAL', 'img55.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 2),                                
                                (60, TRUE, 'SOCIAL', 'img54.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 1),
                                (61, TRUE, 'SOCIAL', 'img53.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 11),                                
                                (62, TRUE, 'SOCIAL', 'img52.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 11),
                                (63, TRUE, 'SOCIAL', 'img51.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 11),                                
                                (64, TRUE, 'SOCIAL', 'img50.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 11),
                                (65, TRUE, 'SOCIAL', 'img49.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 12),                                
                                (66, TRUE, 'SOCIAL', 'img48.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 12),
                                (67, TRUE, 'SOCIAL', 'img47.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 12),                                
                                (68, TRUE, 'SOCIAL', 'img46.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 12),
                                (69, TRUE, 'SOCIAL', 'img45.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 12),                                
                                (70, TRUE, 'SOCIAL', 'img44.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 13),
                                (71, TRUE, 'SOCIAL', 'img43.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 13),                                
                                (72, TRUE, 'SOCIAL', 'img42.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 13),
                                (73, TRUE, 'SOCIAL', 'img41.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 13),                                
                                (74, TRUE, 'SOCIAL', 'img40.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 14),
                                (75, TRUE, 'SOCIAL', 'img39.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 14),                                
                                (76, TRUE, 'SOCIAL', 'img38.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 14),
                                (77, TRUE, 'SOCIAL', 'img37.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 14),                                
                                (78, TRUE, 'SOCIAL', 'img36.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 15),
                                (79, TRUE, 'SOCIAL', 'img35.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 15),                                
                                (80, TRUE, 'SOCIAL', 'img34.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 15),
                                (81, TRUE, 'SOCIAL', 'img33.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Doe sangue', 15),                                
                                (82, TRUE, 'SOCIAL', 'img32.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Campanha Esperança Social', 16),
                                (83, TRUE, 'SOCIAL', 'img31.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Campanha Criança Esperança', 16),                                
                                (84, TRUE, 'SOCIAL', 'img30.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 16),
                                (85, TRUE, 'SOCIAL', 'img29.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Campanha Social Especial', 16),                                
                                (86, TRUE, 'SOCIAL', 'img28.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Coisas que importam', 17),
                                (87, TRUE, 'SOCIAL', 'img27.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Campanha Paz de Luz', 17),                                
                                (88, TRUE, 'SOCIAL', 'img26.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Campanha Mais Vida', 17),
                                (89, TRUE, 'SOCIAL', 'img25.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Campanha Amor Social', 17),                                
                                (90, TRUE, 'SOCIAL', 'img24.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Campanha Vida Plena', 18),
                                (91, TRUE, 'SOCIAL', 'img23.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Campanha Verde Vida', 18),                                
                                (92, TRUE, 'SOCIAL', 'img22.jpg', 'O ministério Servos vem há anos abençoando muitas famílias, crianças, moradores de rua e dependentes químicos.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Campanha Luz do Dia', 18),
                                (93, TRUE, 'SOCIAL', 'img21.jpg', 'Doação de sangue: para quem doa são alguns minutos, para quem recebe é uma vida inteira.', NULL, 'Essa é uma campanha que tem o objetivo de ajudar pessoas que estão passando por momentos de necessidade.', 'PROGRESS', 'Campanha Mais Parceria', 18);






INSERT INTO `item` VALUES (1, 50, 'qualquer tipo', 'arroz', 100, 'QUILOGRAMA', 1),
                          (2, 700, 'qualquer tipo', 'feijão', 800, 'QUILOGRAMA', 1),
                          (3, 2000, 'qualquer tipo', 'macarrao', 2321, 'QUILOGRAMA', 1),
                          (4, 10, 'qualquer tipo', 'farinha', 100, 'QUILOGRAMA', 2),
                          (5, 20, 'qualquer tipo', 'açúcar', 103, 'QUILOGRAMA', 2),
                          (6, 206, 'qualquer tipo', 'leite em pó', 321, 'QUILOGRAMA', 3),
                          (7, 530, 'qualquer tipo', 'café', 1000, 'QUILOGRAMA', 3),
                          (8, 90, 'qualquer tipo', 'manteiga', 321, 'QUILOGRAMA', 3),
                          (9, 540, 'qualquer tipo', 'cuscuz', 1110, 'QUILOGRAMA', 3),
                          (10, 2000, 'qualquer tipo', 'produtos de limpeza', 2321, 'QUILOGRAMA', 3),

                          (11, 50, 'MASCULINO OU FEMININO', 'roupa infantil', 100, 'UNIDADE', 1),
                          (12, 700, 'MASCULINO OU FEMININO', 'roupa ADULTA', 800, 'UNIDADE', 1),
                          (13, 2000, 'MASCULINO OU FEMININO', 'sapatos sandalhas', 2321, 'UNIDADE', 1),
                          (14, 10, 'MASCULINO OU FEMININO', 'roupa de frio', 100, 'UNIDADE', 2),
                          (15, 20, 'MASCULINO OU FEMININO', 'roupa de frio infantil', 103, 'UNIDADE', 2),
                          (16, 206, 'MASCULINO OU FEMININO', 'shorts', 321, 'UNIDADE', 3),
                          (17, 530, 'MASCULINO OU FEMININO', 'shorts infantis', 1000, 'UNIDADE', 3),
                          (18, 90, 'MASCULINO OU FEMININO', 'calça jeans', 321, 'UNIDADE', 3),
                          (19, 540, 'MASCULINO OU FEMININO', 'jeans infantis', 1110, 'UNIDADE', 3),
                          (20, 201, 'MASCULINO OU FEMININO', 'cobertas e lençóis', 421, 'UNIDADE', 4),

                          (21, 50, 'Tamanho P e M ', 'fraldas', 100, 'UNIDADE', 4),
                          (22, 270, 'Infantil', 'condicionador', 800, 'UNIDADE', 4),
                          (23, 500, 'Infantil', 'sabonete', 2321, 'UNIDADE', 5),
                          (24, 810, 'Infantil', 'shampoo', 1090, 'UNIDADE', 5),
                          (25, 20, 'Infantil', 'pasta de Dente', 103, 'UNIDADE', 5),
                          (26, 206, 'Infantil', 'leite em pó', 321, 'UNIDADE', 6),
                          (27, 530, 'Infantil', 'escova de Dente', 1000, 'UNIDADE', 6),
                          (28, 90, 'Infantil', 'carrinho', 321, 'UNIDADE', 6),
                          (29, 540, 'Infantil', 'roupas em geral', 1110, 'UNIDADE', 7),
                          (30, 2040, 'Infantil', 'toca de frio', 2321, 'UNIDADE', 7),

                          (31, 10, 'qualquer tipo', 'sabão em pó', 102, 'QUILOGRAMA', 7),
                          (32, 300, 'qualquer tipo', 'sabão em barra', 400, 'UNIDADE', 8),
                          (33, 2000, 'qualquer tipo', 'desinfetante', 2321, 'UNIDADE', 8),
                          (34, 10, 'qualquer tipo', 'detergente', 100, 'UNIDADE', 8),
                          (35, 20, 'qualquer tipo', 'esponja de banho', 103, 'UNIDADE', 77),
                          (36, 206, 'qualquer tipo', 'esponja de lavar louça', 321, 'UNIDADE', 77),
                          (37, 530, 'qualquer tipo', 'papel higiênico', 1000, 'UNIDADE', 77),
                          (38, 90, 'qualquer tipo', 'água sanitária', 321, 'UNIDADE', 10),
                          (39, 40, 'qualquer tipo', 'vasoura', 110, 'UNIDADE', 10),
                          (40, 2000, 'qualquer tipo', 'pano de chão', 2321, 'UNIDADE', 10),

                          -- seperando por campanhas

                          (41, 50, 'qualquer tipo', 'arroz', 100, 'QUILOGRAMA', 1),
                          (42, 400, 'qualquer tipo', 'feijão', 800, 'QUILOGRAMA', 1),
                          (43, 1600, 'qualquer tipo', 'macarrao', 2321, 'QUILOGRAMA', 1),
                          (44, 16, 'qualquer tipo', 'farinha', 100, 'QUILOGRAMA', 1),
                          (45, 21, 'qualquer tipo', 'açúcar', 103, 'QUILOGRAMA', 1),
                          (46, 206, 'qualquer tipo', 'leite em pó', 321, 'QUILOGRAMA', 1),
                          (47, 530, 'qualquer tipo', 'café', 1000, 'QUILOGRAMA', 1),
                          (48, 90, 'qualquer tipo', 'manteiga', 321, 'QUILOGRAMA', 1),
                          (49, 540, 'qualquer tipo', 'cuscuz', 1110, 'QUILOGRAMA', 1),
                          (50, 2000, 'qualquer tipo', 'produtos de limpeza', 2321, 'QUILOGRAMA', 1),

                          (51, 50, 'qualquer tipo', 'arroz', 100, 'QUILOGRAMA', 2),
                          (52, 700, 'qualquer tipo', 'feijão', 800, 'QUILOGRAMA', 2),
                          (53, 2000, 'qualquer tipo', 'macarrao', 2321, 'QUILOGRAMA', 2),
                          (54, 10, 'qualquer tipo', 'farinha', 100, 'QUILOGRAMA', 2),
                          (55, 20, 'qualquer tipo', 'açúcar', 103, 'QUILOGRAMA', 2),
                          (56, 206, 'qualquer tipo', 'leite em pó', 321, 'QUILOGRAMA', 3),
                          (57, 530, 'qualquer tipo', 'café', 1000, 'QUILOGRAMA', 3),
                          (58, 90, 'qualquer tipo', 'manteiga', 321, 'QUILOGRAMA', 3),
                          (59, 540, 'qualquer tipo', 'cuscuz', 1110, 'QUILOGRAMA', 3),
                          (60, 2000, 'qualquer tipo', 'produtos de limpeza', 2321, 'QUILOGRAMA', 3),

                          (71, 50, 'MASCULINO OU FEMININO', 'roupa infantil', 100, 'UNIDADE', 4),
                          (72, 700, 'MASCULINO OU FEMININO', 'roupa ADULTA', 800, 'UNIDADE', 4),
                          (73, 2000, 'MASCULINO OU FEMININO', 'sapatos sandalhas', 2321, 'UNIDADE', 4),
                          (74, 10, 'MASCULINO OU FEMININO', 'roupa de frio', 100, 'UNIDADE', 4),
                          (75, 20, 'MASCULINO OU FEMININO', 'roupa de frio infantil', 103, 'UNIDADE', 4),
                          (76, 206, 'MASCULINO OU FEMININO', 'shorts', 321, 'UNIDADE', 4),
                          (77, 530, 'MASCULINO OU FEMININO', 'shorts infantis', 1000, 'UNIDADE', 4),
                          (78, 90, 'MASCULINO OU FEMININO', 'calça jeans', 321, 'UNIDADE', 4),
                          (79, 540, 'MASCULINO OU FEMININO', 'jeans infantis', 1110, 'UNIDADE', 4),
                          (80, 201, 'MASCULINO OU FEMININO', 'cobertas e lençóis', 421, 'UNIDADE', 4),

                          (91, 50, 'MASCULINO OU FEMININO', 'roupa infantil', 100, 'UNIDADE', 5),
                          (92, 700, 'MASCULINO OU FEMININO', 'roupa ADULTA', 800, 'UNIDADE', 5),
                          (93, 2000, 'MASCULINO OU FEMININO', 'sapatos sandalhas', 2321, 'UNIDADE', 5),
                          (94, 10, 'MASCULINO OU FEMININO', 'roupa de frio', 100, 'UNIDADE', 5),
                          (95, 20, 'MASCULINO OU FEMININO', 'roupa de frio infantil', 103, 'UNIDADE', 5),
                          (96, 206, 'MASCULINO OU FEMININO', 'shorts', 321, 'UNIDADE', 5),
                          (97, 530, 'MASCULINO OU FEMININO', 'shorts infantis', 1000, 'UNIDADE', 5),
                          (98, 90, 'MASCULINO OU FEMININO', 'calça jeans', 321, 'UNIDADE', 5),
                          (99, 540, 'MASCULINO OU FEMININO', 'jeans infantis', 1110, 'UNIDADE', 5),
                          (100, 201, 'MASCULINO OU FEMININO', 'cobertas e lençóis', 421, 'UNIDADE', 5),

                          (101, 50, 'Tamanho P e M ', 'fraldas', 100, 'UNIDADE', 43),
                          (102, 270, 'Infantil', 'condicionador', 800, 'UNIDADE', 43),
                          (103, 500, 'Infantil', 'sabonete', 2321, 'UNIDADE', 43),
                          (104, 810, 'Infantil', 'shampoo', 1090, 'UNIDADE', 43),
                          (105, 20, 'Infantil', 'pasta de Dente', 103, 'UNIDADE', 43),
                          (106, 206, 'Infantil', 'leite em pó', 321, 'UNIDADE', 7),
                          (107, 530, 'Infantil', 'escova de Dente', 1000, 'UNIDADE', 7),
                          (108, 90, 'Infantil', 'carrinho', 321, 'UNIDADE', 7),
                          (109, 540, 'Infantil', 'roupas em geral', 1110, 'UNIDADE', 7),
                          (110, 2040, 'Infantil', 'toca de frio', 2321, 'UNIDADE', 7),

                          (111, 10, 'qualquer tipo', 'sabão em pó', 102, 'QUILOGRAMA', 9),
                          (112, 300, 'qualquer tipo', 'sabão em barra', 400, 'UNIDADE', 9),
                          (113, 2000, 'qualquer tipo', 'desinfetante', 2321, 'UNIDADE', 9),
                          (114, 10, 'qualquer tipo', 'detergente', 100, 'UNIDADE', 9),
                          (115, 20, 'qualquer tipo', 'esponja de banho', 103, 'UNIDADE', 9),
                          (116, 206, 'qualquer tipo', 'esponja de lavar louça', 321, 'UNIDADE', 10),
                          (117, 530, 'qualquer tipo', 'papel higiênico', 1000, 'UNIDADE', 10),
                          (118, 90, 'qualquer tipo', 'água sanitária', 321, 'UNIDADE', 10),
                          (119, 40, 'qualquer tipo', 'vasoura', 110, 'UNIDADE', 10),
                          (120, 2000, 'qualquer tipo', 'pano de chão', 2321, 'UNIDADE', 10),

                          (121, 50, 'Tamanho P e M ', 'fraldas', 100, 'UNIDADE', 11),
                          (122, 270, 'Infantil', 'condicionador', 800, 'UNIDADE', 11),
                          (123, 500, 'Infantil', 'sabonete', 2321, 'UNIDADE',11),
                          (124, 810, 'Infantil', 'shampoo', 1090, 'UNIDADE', 11),
                          (125, 20, 'Infantil', 'pasta de Dente', 103, 'UNIDADE', 11),
                          (126, 206, 'Infantil', 'leite em pó', 321, 'UNIDADE', 12),
                          (127, 530, 'Infantil', 'escova de Dente', 1000, 'UNIDADE', 12),
                          (128, 90, 'Infantil', 'carrinho', 321, 'UNIDADE', 12),
                          (129, 540, 'Infantil', 'roupas em geral', 1110, 'UNIDADE', 12),
                          (130, 2040, 'Infantil', 'toca de frio', 2321, 'UNIDADE', 12),
                          (131, 50, 'qualquer tipo', 'arroz', 100, 'QUILOGRAMA', 60),
                          (132, 700, 'qualquer tipo', 'feijão', 800, 'QUILOGRAMA', 60),
                          (133, 2000, 'qualquer tipo', 'macarrao', 2321, 'QUILOGRAMA', 60),
                          (134, 10, 'qualquer tipo', 'farinha', 100, 'QUILOGRAMA', 60),
                          (135, 20, 'qualquer tipo', 'açúcar', 103, 'QUILOGRAMA', 60),
                          (136, 206, 'qualquer tipo', 'leite em pó', 321, 'QUILOGRAMA', 3),
                          (137, 530, 'qualquer tipo', 'café', 1000, 'QUILOGRAMA', 3),
                          (138, 90, 'qualquer tipo', 'manteiga', 321, 'QUILOGRAMA', 3),
                          (139, 540, 'qualquer tipo', 'cuscuz', 1110, 'QUILOGRAMA', 3),
                          (140, 2000, 'qualquer tipo', 'produtos de limpeza', 2321, 'QUILOGRAMA', 3),

                          (141, 33, 'Tamanho P e M ', 'fraldas', 400, 'UNIDADE', 46),
                          (142, 231, 'Infantil', 'condicionador', 300, 'UNIDADE', 46),
                          (143, 1220, 'Infantil', 'sabonete', 2321, 'UNIDADE', 46),
                          (144, 830, 'Infantil', 'shampoo', 1090, 'UNIDADE', 49),
                          (145, 45, 'Infantil', 'pasta de Dente', 103, 'UNIDADE', 49),
                          (146, 210, 'Infantil', 'leite em pó', 321, 'UNIDADE', 49),
                          (147, 230, 'Infantil', 'escova de Dente', 1000, 'UNIDADE', 49),
                          (148, 190, 'Infantil', 'carrinho', 321, 'UNIDADE', 59),
                          (149, 460, 'Infantil', 'roupas em geral', 1110, 'UNIDADE', 59),
                          (150, 1376, 'Infantil', 'toca de frio', 2321, 'UNIDADE', 59),
                          
                          (151, 10, 'qualquer tipo', 'sabão em pó', 102, 'QUILOGRAMA', 59),
                          (152, 300, 'qualquer tipo', 'sabão em barra', 400, 'UNIDADE', 13),
                          (153, 2000, 'qualquer tipo', 'desinfetante', 2321, 'UNIDADE', 13),
                          (154, 10, 'qualquer tipo', 'detergente', 100, 'UNIDADE', 13),
                          (155, 20, 'qualquer tipo', 'esponja de banho', 103, 'UNIDADE', 13),
                          (156, 206, 'qualquer tipo', 'esponja de lavar louça', 321, 'UNIDADE', 13),
                          (157, 530, 'qualquer tipo', 'papel higiênico', 1000, 'UNIDADE', 14),
                          (158, 90, 'qualquer tipo', 'água sanitária', 321, 'UNIDADE', 14),
                          (159, 40, 'qualquer tipo', 'vasoura', 110, 'UNIDADE', 14),
                          (160, 2000, 'qualquer tipo', 'pano de chão', 2321, 'UNIDADE', 14),
                          
                          (161, 10, 'qualquer tipo', 'sabão em pó', 102, 'QUILOGRAMA', 93),
                          (162, 300, 'qualquer tipo', 'sabão em barra', 400, 'UNIDADE', 93),
                          (163, 2000, 'qualquer tipo', 'desinfetante', 2321, 'UNIDADE', 93),
                          (164, 10, 'qualquer tipo', 'detergente', 100, 'UNIDADE', 93),
                          (165, 20, 'qualquer tipo', 'esponja de banho', 103, 'UNIDADE', 93),
                          (166, 206, 'qualquer tipo', 'esponja de lavar louça', 321, 'UNIDADE', 92),
                          (167, 530, 'qualquer tipo', 'papel higiênico', 1000, 'UNIDADE', 92),
                          (168, 90, 'qualquer tipo', 'água sanitária', 321, 'UNIDADE', 92),
                          (169, 40, 'qualquer tipo', 'vasoura', 110, 'UNIDADE', 92),
                          (170, 2000, 'qualquer tipo', 'pano de chão', 2321, 'UNIDADE', 92);

INSERT INTO `denounce` VALUES (1, FALSE, TRUE, '2023-03-02', 'Mensagem da denúncia 01.', 'Título da denúncia 01', 1, 1),
                              (2, FALSE, TRUE, '2022-09-12', 'Mensagem da denúncia 02.', 'Título da denúncia 02', 1, 200),
                              (3, TRUE, TRUE, '2021-08-05', 'Mensagem da denúncia 03.', 'Título da denúncia 03', 3, 200);

INSERT INTO `follow` VALUES (1, 1, 200),
                            (2, 2, 200),
                            (3, 3, 200);

INSERT INTO `enjoy` VALUES (1, 1, 200),
                           (2, 2, 200),
                           (3, 3, 200);

INSERT INTO `trust` VALUES (1, 1, 200),
                           (2, 2, 200),
                           (3, 3, 200);

SET SESSION FOREIGN_KEY_CHECKS=1;
